#!/usr/bin/env bash

venv-exists() {
  [[ -d `venv-get-dir` ]]
}

venv-get-dir() {
  echo "$(basename $(pwd))-venv"
}

venv-activate() {

  local VENV_DIR=`venv-get-dir`

  if [ -d "$VENV_DIR" ]; then
    source "$VENV_DIR/bin/activate"
  fi
}

venv-deactivate() {
  deactivate
}

venv-create() {

  local VENV_DIR=`venv-get-dir`

  if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv $VENV_DIR
  fi
}
